import "./globals.css";
import type { Metadata } from "next";
import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";
import { Box } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <Box
            component="main"
            // sx={{
            //   flexGrow: 1,
            //   // bgcolor: "background.default",
            //   p: 3,
            // }}
          ></Box>
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
